# Copyright 2020 Google LLC
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     https://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '1'
services:
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    environment:
      DATABASE_URL:            mysql2://dev_user:123456@db/my_database?encoding=utf8mb4&collation=utf8mb4_unicode_ci
      LANG:                    en_US.UTF-8
      RAILS_ENV:               development
      RACK_ENV:                development
      RACK_TIMEOUT_LOG_LEVEL:  DEBUG
      S3_ENDPOINT:             http://s3mock:9000
      S3_USE_PATH_STYLE:       "1"
      S3_ACCESS_KEY_ID:       fakeaccesskey
      S3_SECRET_ACCESS_KEY:   fakesecretkey
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: my_database
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: 123456

  storage:
    image: minio/minio
    command: minio server /data
    volumes:
      - storage_data:/data
    restart: always
    environment:
      MINIO_ACCESS_KEY: fakeaccesskey
      MINIO_SECRET_KEY: fakesecretkey
    ports:
      - "9000:9000"

volumes:
    db_data:
    storage_data:



