# From youtube example - Podman - apache, PHP and mariaDB (LAMP) rootless container
# Build: podman build -t localhost:5000/httpd-php:1.0 .

FROM registry.access.redhat.com/ubi8/ubi-init

MAINTAINER elguapo@biomerieux.com

RUN dnf install -y php php-apcu php-intl php-mbstring php-xml php-json php-mysqlnd crontabs cronie iputils net-tools
RUN dnf cleanall

RUN systemctl enable httpd.service

ENTRYPOINT ["/sbin/init"]

CMD ["/sbin/init']


